import fs from 'fs';
import { pinyin } from 'pinyin-pro';

// Helper to delay between API requests
export const delay = (ms) => new Promise(r => setTimeout(r, ms));

// Clean up dictionary explain string into a concise Chinese definition
export function cleanExplain(explainStr, word) {
  if (!explainStr) return '';

  let cleaned = explainStr
    .replace(/^(n|v|adj|adv|prep|conj|pron|art|num|int|vt|vi|abbr)\.\s*/gi, '')
    .trim();

  let parts = cleaned.split(/[；;,，]/).map(s => s.replace(/^[a-z]+\.\s*/gi, '').trim()).filter(Boolean);
  
  if (parts.length === 0) return cleaned;

  let best = parts[0];
  best = best.replace(/\([a-zA-Z\s]+\)/g, '').replace(/（[a-zA-Z\s]+）/g, '').trim();

  return best;
}

// Fetch dict definition from Youdao
export async function fetchDictDef(word) {
  try {
    const res = await fetch(`https://dict.youdao.com/suggest?q=${encodeURIComponent(word.toLowerCase().trim())}&num=1&doctype=json`);
    if (!res.ok) return null;
    const json = await res.json();
    if (json && json.data && json.data.entries && json.data.entries.length > 0) {
      const entry = json.data.entries[0];
      return cleanExplain(entry.explain, word);
    }
  } catch (e) {
    console.error(`Error fetching dict for ${word}:`, e.message);
  }
  return null;
}

// Manual dict override for sight words and high frequency words
export const MANUAL_DICT = {
  "his": "他的",
  "one": "一",
  "they": "他们",
  "i": "我",
  "at": "在",
  "be": "是",
  "this": "这个",
  "have": "有",
  "from": "来自",
  "or": "或者",
  "had": "有（过去式）",
  "by": "通过",
  "word": "单词",
  "but": "但是",
  "not": "不",
  "what": "什么",
  "all": "所有",
  "were": "是（过去式）",
  "we": "我们",
  "when": "当...时",
  "your": "你的",
  "can": "能",
  "said": "说（过去式）",
  "there": "那里",
  "use": "使用",
  "an": "一个",
  "each": "每个",
  "which": "哪一个",
  "she": "她",
  "do": "做",
  "how": "怎样",
  "their": "他们的",
  "if": "如果",
  "will": "将要",
  "up": "向上",
  "other": "其他的",
  "about": "关于",
  "out": "向外",
  "many": "许多",
  "then": "然后",
  "them": "他们",
  "these": "这些",
  "so": "所以",
  "some": "一些",
  "her": "她的",
  "would": "将要（过去式）",
  "make": "制作",
  "like": "喜欢",
  "him": "他",
  "into": "进入",
  "time": "时间",
  "has": "有",
  "look": "看",
  "two": "二",
  "more": "更多",
  "write": "写",
  "go": "去",
  "see": "看见",
  "number": "数字",
  "no": "不",
  "way": "方法",
  "could": "能（过去式）",
  "people": "人们",
  "my": "我的",
  "than": "比",
  "first": "第一",
  "water": "水",
  "been": "是（完成时）",
  "call": "呼叫",
  "who": "谁",
  "oil": "油",
  "its": "它的",
  "now": "现在",
  "find": "找到",
  "long": "长的",
  "down": "向下",
  "day": "一天",
  "did": "做（过去式）",
  "get": "得到",
  "come": "来",
  "made": "制作（过去式）",
  "may": "可能",
  "part": "部分",
  "over": "在...上方",
  "new": "新的",
  "sound": "声音",
  "take": "拿",
  "only": "只有",
  "little": "小的",
  "work": "工作",
  "know": "知道",
  "place": "地方",
  "years": "年份",
  "year": "年",
  "live": "生活",
  "me": "我",
  "back": "返回",
  "give": "给予",
  "most": "最多的",
  "very": "非常",
  "after": "在...之后",
  "thing": "事物",
  "our": "我们的",
  "just": "仅仅",
  "name": "名字",
  "good": "好的",
  "sentence": "句子",
  "man": "男人",
  "think": "思考",
  "say": "说",
  "great": "伟大的",
  "where": "在哪里",
  "help": "帮助",
  "through": "穿过",
  "much": "许多",
  "before": "在...之前",
  "line": "线",
  "right": "正确的",
  "too": "太",
  "means": "意味着",
  "old": "旧的",
  "any": "任何",
  "same": "相同的",
  "tell": "告诉",
  "boy": "男孩",
  "follow": "跟随",
  "came": "来（过去式）",
  "want": "想要",
  "show": "展示",
  "also": "也",
  "around": "周围",
  "form": "形式",
  "three": "三",
  "small": "小的",
  "set": "设置",
  "put": "放置",
  "end": "结束",
  "does": "做",
  "another": "另一个",
  "well": "好",
  "large": "大的",
  "must": "必须",
  "big": "大的",
  "even": "甚至",
  "such": "这样的",
  "because": "因为",
  "turn": "转动",
  "here": "这里",
  "why": "为什么",
  "ask": "询问",
  "went": "去（过去式）",
  "men": "男人们",
  "read": "阅读",
  "need": "需要",
  "land": "土地",
  "different": "不同的",
  "home": "家",
  "us": "我们",
  "move": "移动",
  "try": "尝试",
  "kind": "种类",
  "hand": "手",
  "picture": "图片",
  "again": "再次",
  "change": "改变",
  "off": "关掉",
  "play": "玩",
  "spell": "拼写",
  "air": "空气",
  "away": "离开",
  "animal": "动物",
  "house": "房子",
  "point": "点",
  "page": "页",
  "letter": "信件",
  "mother": "母亲",
  "answer": "回答",
  "found": "找到（过去式）",
  "study": "学习",
  "still": "仍然",
  "learn": "学习",
  "should": "应该",
  "america": "美国",
  "world": "世界",
  "high": "高的",
  "every": "每一个",
  "near": "靠近",
  "add": "添加",
  "food": "食物",
  "between": "在...之间",
  "own": "自己的",
  "below": "在...下方",
  "country": "国家",
  "plant": "植物",
  "last": "最后的",
  "school": "学校",
  "father": "父亲",
  "keep": "保持",
  "tree": "树",
  "never": "从不",
  "start": "开始",
  "city": "城市",
  "earth": "地球",
  "eyes": "眼睛",
  "light": "光",
  "thought": "想法",
  "head": "头",
  "under": "在...下面",
  "story": "故事",
  "saw": "看见（过去式）",
  "left": "左边",
  "don't": "不要",
  "few": "少数",
  "while": "当...的时候",
  "along": "沿着",
  "might": "可能",
  "close": "关闭",
  "something": "某事",
  "seem": "似乎",
  "next": "下一个",
  "hard": "困难的",
  "open": "打开",
  "example": "例子",
  "begin": "开始",
  "life": "生活",
  "always": "总是",
  "those": "那些",
  "both": "两者都",
  "paper": "纸",
  "together": "一起",
  "got": "得到（过去式）",
  "group": "小组",
  "often": "经常",
  "run": "跑步",
  "important": "重要的",
  "until": "直到",
  "children": "孩子们",
  "side": "侧面",
  "feet": "脚",
  "car": "汽车",
  "mile": "英里",
  "night": "夜晚",
  "walk": "行走",
  "white": "白色",
  "sea": "大海",
  "began": "开始（过去式）",
  "grow": "生长",
  "took": "拿（过去式）",
  "river": "河流",
  "four": "四",
  "carry": "携带",
  "state": "状态",
  "once": "一次",
  "book": "书",
  "hear": "听见",
  "stop": "停止",
  "without": "没有",
  "second": "第二",
  "late": "迟的",
  "miss": "想念",
  "idea": "想法",
  "enough": "足够的",
  "eat": "吃",
  "face": "脸",
  "watch": "观看",
  "far": "远的",
  "indian": "印第安人",
  "really": "真正地",
  "almost": "几乎",
  "let": "让",
  "above": "在...上方",
  "girl": "女孩",
  "sometimes": "有时",
  "mountain": "山",
  "cut": "剪切",
  "young": "年轻的",
  "talk": "谈话",
  "soon": "很快",
  "list": "列表",
  "song": "歌曲",
  "being": "存在",
  "going": "去",
  "quick": "快速的",
  "sell": "卖",
  "nature": "自然",
  "minute": "分钟",
  "jobs": "工作",
  "leaving": "离开",
  "forces": "力量",
  "immediately": "立刻",
  "additional": "附加的",
  "absolutely": "绝对地",
  "numbers": "数字",
  "score": "得分"
};
